### ISSUE TITLE
Adding more word lists

### ISSUE THREAD

**Issue by twmr** [progfolio/wordel#5]
Maybe you can mention from in the README how the bundled word lists were generated. This would be helpful for the users (like me) that want to generate other word lists.

Thx

**Comment by progfolio** [comment]
There's not much to say, unfortunately. The word list just needs to be one word per line.
I just used a previously existing scrabble list and the list of wordel words for the bundled lists.

One thing I will say, is if you plan on making your own list, you'll want to add enough words so that users can guess incorrect words and still get clues. That's less a technical point and more just a game design point, though.

**Comment by progfolio** [comment]
I've added a note to the README which points this out.
